### ISSUE TITLE
Questions for the client

### ISSUE THREAD

**Issue by LMihal** [TIS2024-FMFI/Lab.Cafe#22]
Súhlasí s návrhom špecifikácie?
V akom stave je systém 3D tlačiarní?
Ak niečo existuje, dá sa to zrecyklovať?
Čo všetko je potrebné vyrobiť/prerobiť na systéme tlačiarní?
Existuje modul pre POS terminál?
Ako sa bude napájať do papayaPOS? (káblom, či spojením)
Existuje nejaké API pre papayaPOS?
Ako zostrojiť POS terminál?

**Comment by michalvanco0** [comment]
Otázky:
V akom stave je systém 3D tlačiarní?, 

Ak niečo existuje, dá sa to zrecyklovať?
Čo všetko je potrebné vyrobiť/prerobiť na systéme tlačiarní?
 

= Každá tlačiareň má dedikované raspberry pi s Octoprintom nainstalovanym.
= V otello je CRUD pre nastavenie tlaciarni a pozeranie jobov (robene celkom rychlo cez chatgpt). je tam pridavanie tlaciarni, pozeranie vsetykch jobov, a dokonca logovanie progressu tlace (co je trocha overkill kvoli mnozstvu dat)
= Na githube su skripty k samotnemu trackovaniu tlaciarni. Tie starsie sme aktivne pouzivali. Tie novsie som skusal nasadit aby sa odstranili problemy s konektivitou. Bohuzial to nie je uplne dotiahnute. Problem bol s tym, ze ked sa pouzival webhook v Octopi (teda Octopi volalo na server), tak dost random to posielalo strukturu dat. A nevedel som zistit cim to je. 
= Zacal som teda robit na python scripte, ktory by iniciativne kazdych 30 sekund sam checkol kazdy octoprint (teda my volame Octoprint). Tam sa na requeste na active job vracali vzdy plne data
=

 

Existuje modul pre POS terminál?
Ako sa bude napájať do papayaPOS? (káblom, či spojením)
Existuje nejaké API pre papayaPOS?
Ako zostrojiť POS terminál?

Modul k POS terminalu existuje. Je to prototyp, ktory ma za ulohu volat end point v otellovy ked sa prilozi karta.
Na papayaPOS sa priamo nenapaja. Vyuzivame workaround. Papaya ako taka umoznuje napojenie na hotelovy system. Namiesto endpointu hoteloveho systemu dame endpoint na otello. Tym padom, ked sa plati blocek na hotelovy system, data pritecu k nam do otella.

Cele flow je taketo: 
clen Labu si objedna na bare
barman nahodi produkty do kasy
clen (nazvime ho Aktivny clen) prilozi kartu k LabMemberTerminalu (LMT)
LMT zavola endpoint na otellovi. Aktivny clen sa v otellovy ulozi (kludne ako novy zaznam v databaze)
barman vyberie moznost platby na hotelovy ucet, to sposobi to, ze PapayaPOS zavola prednastaveny endpoint, ktory by mal vratit aktivne bookingy (teda v nasom ponimani vrati Aktivneho clena
barman potvrdi vyberom aktivneho clena, tym sa odosle na ten isty endpoint v otellovi cely aktivny blocek a v papayaPOS sa uzavrie s tym ze bol uhradeny cez hotelovy system
endpoint dany blok ulozi do databazy 
- co treba doriesit (ako dlho nechat aktivneho clena, kym ho neodhlasi, a ako to cele sprocesovat? : priklad, Aktivny clen si nieco objedna. Prilozi karticku k LMT. Barman nasledne zisti ze produkt nema. Jedna moznost je zrusit aktivneho clena na obrazovke (aby sa nestalo ze si na jeho ucet objedna niekto iny), alebo nastavit v LTM timeout, kedy sa odosle do otella null clen, tym padom sa nebude dat platit na hotelovy system, lebo PapayaPOS v prvom kroku vrati nula Aktivnych clenov.
 

 
Vieme sa dohodnúť na termíne kedy by sme to priamo vyskúšali nakódiť a otestovať?

Vieme. Aj ked mi je trapne znova slubit datum a potom sa neukazat. Verim ze sa to uz nestane. Za mna idealne niekedy o 9 rano. Ale aj dnes som planoval byt v praci od 9tej, je 10:30 a este stale robim z domu.
Jedna z mosnosti je, ze si donesiete komp, a dame to ako call, keby sa mi nepodarilo prist in person. Cez mobil to je blbost robit.
